### ISSUE TITLE
undefined method `request_uri' for #<URI::Generic localhost:3000/api/frontend/settings> Did you mean? require

### ISSUE THREAD

**Issue by Maelff** [divinity666/ruby-grafana-reporter#16]
**Describe the issue**
Using the reporter on docker, I try to generate a pdf document with the grafana panels. 
I modified the demo_report to test it, and wanted to show a panel. The PDF succesfully generate, but instead of the panels, I get the error : " undefined method `request_uri' for #<URI::Generic localhost:3000/api/frontend/settings> Did you mean? require "
I tried many things to fix it, such as changing the host in the configuration file, that ended only changing the adresse in the error message.

**Application call**
 - type of call [webservice or single-run]: webservice
 - call of reporter [e.g. ruby-grafana-reporter -c myconfig]: 
 - call of report creation, if running as webservice [e.g. http://localhost/render?var-template=test]: http://dev.asciidoctor/render?var-template=demo_report
 
**Template file (if applicable)**
 - filename: demo_report.adoc
 - relevant part of template file:

`grafana_panel_image::2[dashboard="fH4MVUpnk"]`

**Configuration file**
 - created with configuration wizard version [e.g. 0.3.0 or MANUAL]: 
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
 
```
grafana:
 default:
    host: localhost:3000
    api_key: *****

grafana-reporter:
  check-for-updates: 1
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 24
  webservice-port: 8815

default-document-attributes:
  imagesdir: ./images


```
**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: Ubuntu
 - Environment [e.g. source, gem, docker or windows-exe]: docker
 - ruby Version, if source or gem environment [e.g. 2.3.7]: 3.0.2
 - reporter Version [e.g. 0.3.0]: 0.5.0
