### ISSUE TITLE
The reporter failed with GrafanaError: The datasource request returned with an unsupported response format

### ISSUE THREAD

**Issue by emanzx** [divinity666/ruby-grafana-reporter#28]
**Describe the issue**
I try to use grafana_panel_query_value in my report but the reporter return an error mentioning unsupported response format. Below are full log.

```
I, [2022-06-27T07:45:18.579079 #74862]  INFO -- : Server listening on port 5050...
I, [2022-06-27T07:45:38.929898 #74862]  INFO -- : 1 report(s) in progress: 0% (running 0 secs)
I, [2022-06-27T07:45:38.930262 #74862]  INFO -- : Report started at 2022-06-27 07:45:38 +0000
I, [2022-06-27T07:45:38.930310 #74862]  INFO -- : You are running ruby-grafana-reporter version 0.5.4.
I, [2022-06-27T07:45:43.947681 #74862]  INFO -- : 1 report(s) in progress: 6% (running 5 secs)
I, [2022-06-27T07:45:48.967751 #74862]  INFO -- : 1 report(s) in progress: 6% (running 10 secs)
I, [2022-06-27T07:45:54.014023 #74862]  INFO -- : 1 report(s) in progress: 6% (running 15 secs)
I, [2022-06-27T07:45:59.067761 #74862]  INFO -- : 1 report(s) in progress: 6% (running 20 secs)
E, [2022-06-27T07:46:02.224818 #74862] ERROR -- : GrafanaError: The specified panel id ':70' does not exist on the dashboard 'RzLX0d3nk'. (Grafana::PanelDoesNotExistError)
I, [2022-06-27T07:46:04.093955 #74862]  INFO -- : 1 report(s) in progress: 85% (running 25 secs)
I, [2022-06-27T07:46:09.147691 #74862]  INFO -- : 1 report(s) in progress: 85% (running 30 secs)
I, [2022-06-27T07:46:14.167670 #74862]  INFO -- : 1 report(s) in progress: 85% (running 35 secs)
I, [2022-06-27T07:46:19.223961 #74862]  INFO -- : 1 report(s) in progress: 85% (running 40 secs)
I, [2022-06-27T07:46:24.247214 #74862]  INFO -- : 1 report(s) in progress: 85% (running 45 secs)
I, [2022-06-27T07:46:29.266857 #74862]  INFO -- : 1 report(s) in progress: 85% (running 50 secs)
I, [2022-06-27T07:46:34.347697 #74862]  INFO -- : 1 report(s) in progress: 85% (running 55 secs)
I, [2022-06-27T07:46:39.366280 #74862]  INFO -- : 1 report(s) in progress: 85% (running 60 secs)
I, [2022-06-27T07:46:44.409345 #74862]  INFO -- : 1 report(s) in progress: 85% (running 65 secs)
I, [2022-06-27T07:46:49.414752 #74862]  INFO -- : 1 report(s) in progress: 85% (running 70 secs)
I, [2022-06-27T07:46:54.422882 #74862]  INFO -- : 1 report(s) in progress: 85% (running 75 secs)
I, [2022-06-27T07:46:59.447698 #74862]  INFO -- : 1 report(s) in progress: 85% (running 80 secs)
I, [2022-06-27T07:47:04.467683 #74862]  INFO -- : 1 report(s) in progress: 85% (running 85 secs)
I, [2022-06-27T07:47:09.524027 #74862]  INFO -- : 1 report(s) in progress: 87% (running 90 secs)
I, [2022-06-27T07:47:14.567711 #74862]  INFO -- : 1 report(s) in progress: 87% (running 95 secs)
I, [2022-06-27T07:47:19.583938 #74862]  INFO -- : 1 report(s) in progress: 87% (running 100 secs)
I, [2022-06-27T07:47:24.613933 #74862]  INFO -- : 1 report(s) in progress: 87% (running 105 secs)
I, [2022-06-27T07:47:29.647715 #74862]  INFO -- : 1 report(s) in progress: 87% (running 110 secs)
I, [2022-06-27T07:47:34.657214 #74862]  INFO -- : 1 report(s) in progress: 87% (running 115 secs)
I, [2022-06-27T07:47:39.667705 #74862]  INFO -- : 1 report(s) in progress: 87% (running 120 secs)
I, [2022-06-27T07:47:44.683911 #74862]  INFO -- : 1 report(s) in progress: 87% (running 125 secs)
I, [2022-06-27T07:47:49.712368 #74862]  INFO -- : 1 report(s) in progress: 87% (running 130 secs)
I, [2022-06-27T07:47:54.767666 #74862]  INFO -- : 1 report(s) in progress: 87% (running 135 secs)
I, [2022-06-27T07:47:59.832317 #74862]  INFO -- : 1 report(s) in progress: 87% (running 140 secs)
I, [2022-06-27T07:48:04.842883 #74862]  INFO -- : 1 report(s) in progress: 87% (running 145 secs)
I, [2022-06-27T07:48:09.855256 #74862]  INFO -- : 1 report(s) in progress: 87% (running 150 secs)
I, [2022-06-27T07:48:14.867724 #74862]  INFO -- : 1 report(s) in progress: 87% (running 155 secs)
I, [2022-06-27T07:48:19.905231 #74862]  INFO -- : 1 report(s) in progress: 87% (running 160 secs)
I, [2022-06-27T07:48:24.947688 #74862]  INFO -- : 1 report(s) in progress: 89% (running 166 secs)
I, [2022-06-27T07:48:29.967697 #74862]  INFO -- : 1 report(s) in progress: 91% (running 171 secs)
I, [2022-06-27T07:48:35.037928 #74862]  INFO -- : 1 report(s) in progress: 91% (running 176 secs)
I, [2022-06-27T07:48:40.047741 #74862]  INFO -- : 1 report(s) in progress: 91% (running 181 secs)
I, [2022-06-27T07:48:45.099682 #74862]  INFO -- : 1 report(s) in progress: 91% (running 186 secs)
I, [2022-06-27T07:48:50.140130 #74862]  INFO -- : 1 report(s) in progress: 91% (running 191 secs)
I, [2022-06-27T07:48:55.145869 #74862]  INFO -- : 1 report(s) in progress: 91% (running 196 secs)
I, [2022-06-27T07:49:00.167704 #74862]  INFO -- : 1 report(s) in progress: 91% (running 201 secs)
I, [2022-06-27T07:49:05.199726 #74862]  INFO -- : 1 report(s) in progress: 91% (running 206 secs)
I, [2022-06-27T07:49:10.267661 #74862]  INFO -- : 1 report(s) in progress: 91% (running 211 secs)
I, [2022-06-27T07:49:15.347678 #74862]  INFO -- : 1 report(s) in progress: 91% (running 216 secs)
I, [2022-06-27T07:49:20.367680 #74862]  INFO -- : 1 report(s) in progress: 91% (running 221 secs)
I, [2022-06-27T07:49:25.427283 #74862]  INFO -- : 1 report(s) in progress: 91% (running 226 secs)
I, [2022-06-27T07:49:30.447672 #74862]  INFO -- : 1 report(s) in progress: 91% (running 231 secs)
I, [2022-06-27T07:49:35.464028 #74862]  INFO -- : 1 report(s) in progress: 93% (running 236 secs)
I, [2022-06-27T07:49:40.522905 #74862]  INFO -- : 1 report(s) in progress: 93% (running 241 secs)
I, [2022-06-27T07:49:45.583932 #74862]  INFO -- : 1 report(s) in progress: 93% (running 246 secs)
E, [2022-06-27T07:49:48.379877 #74862] ERROR -- : GrafanaError: The datasource request returned with an unsupported response format (received: {"status":"success","data":{"resultType":"vector","result":[]}}). (Grafana::UnsupportedQueryResponseReceivedError)
I, [2022-06-27T07:49:48.550937 #74862]  INFO -- : Report creation ended after 250 seconds with status 'finished'
```
here are the query
```
sum(netdata_system_cpu_percentage_average{dimension!="idle",instance="xxxx.local"})
```

here are info I get from grafana query inspector
```
{
  "request": {
    "url": "api/datasources/proxy/7/api/v1/query",
    "method": "POST",
    "data": {
      "query": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\",instance=\"xxxx.local\"})",
      "time": 1656319407
    },
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {},
          "value": [
            1656319407,
            "15.6938131"
          ]
        }
      ]
    }
  }
}
```
**Application call**
 - type of call: webservice
 - call of reporter: ruby-grafana-reporter
 - call of report creation: curl "http://localhost:5050/render?var-template=mahb_report"

**Template file (if applicable)**
 - filename: mahb_report
 - relevant part of template file:
```
[width=65%, role=center]
|=======================
|Host Name:         |grafana_panel_property:22["title",dashboard="RzLX0d3nk"]
|IP:                |grafana_panel_property:23["title",dashboard="RzLX0d3nk"]
|Model:             |grafana_panel_property:24["description",dashboard="RzLX0d3nk"]
|CPU Usage:	        |grafana_panel_query_value:7[query="A",dashboard="RzLX0d3nk",instant="true"]
|Memory Usage:	    |37.9% out of 16GB
|Storage Usage:	    |29%
|Serial Number:	    |5430GIZ
|License Expiry:	|31/12/2023
|Support Expiry:	|31/12/2023
|=======================
```

**Configuration file**
 - created with configuration wizard version [e.g. 0.3.0 or MANUAL]: 0.5.4
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
# This configuration has been built with the configuration wizard.

grafana:
  default:
    host: http://cm.xxx.xxx.net:5555
    api_key: xxxx


grafana-reporter:
# Specifies how often the reporter shall check for newer versions [number of days].
# You may set check-for-updates to 0 to disable
  check-for-updates: 1
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 24
  webservice-port: 5050
# you may want to configure the following webhook callbacks to get informed on certain events
#  callbacks:
#    all:
#      - <<your_callback_url>>
#      - ...
#    on_before_create:
#      - <<your_callback_url>>
#      - ...
#    on_after_cancel:
#      - <<your_callback_url>>
#      - ...
#    on_after_finish:
#      - <<your_callback_url>>
#      - ...

default-document-attributes:
  imagesdir: ./images
```

**Environment (please complete the following information):**
 - OS : FreeBSD 13.1
 - Environment : gem
 - ruby Version, if source or gem environment [e.g. 2.3.7]: ruby 2.6.8p205 (2021-07-07 revision 67951) [x86_64-freebsd13.0]
 - reporter Version [e.g. 0.3.0]: 0.5.4
