### ISSUE TITLE
Help with Getting Started

### ISSUE THREAD

**Issue by nat-ray** [divinity666/ruby-grafana-reporter#34]
**Describe the issue**
I am trying to create a simple report of a Grafana dashboard. I have installed the tool to my local and ran the wizard. I see the demo_report.adoc file is there, but am not sure I understand where to go from here. 

When creating our own template files, is this supposed to point to the specific dashboard that we want to create the report on? Is there any simple guide that shows how to go about doing this using one dashboard? 

**Configuration file**
 - created with configuration wizard version
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
# This configuration has been built with the configuration wizard.

grafana:
  default:
    host: https://URL:443
    api_key: XXXXX
```

**Environment (please complete the following information):**
 - OS: OSX
 - Grafana version [e.g. 6.3.4]: 7.4.1
 - Environment: Grafana is running in Kubernetes  
 - Ruby Version, if source or gem environment: ruby 3.1.2p20
 - Reporter version: 0.6.2
