### ISSUE TITLE
grafana_sql_value and grafana_sql_table result in undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by kbmanseau** [divinity666/ruby-grafana-reporter#35]
**Describe the issue**
I am evaluating the abilities of the ruby-reporter and when I was testing grafana_sql_value I ran into some issues. I have a dev environment so I am able to quickly test different grafana versions if needed but so far I was trying to match my prod deployment running grafana 7.2.2. I have also tested on 8.2.6m, 8.3.5 and latest. Whenever I try and use the sql calls I get 
`undefined method 'id' for nil:NilClass`

Attaching debug:
```
I, [2022-11-10T14:12:44.959074 #117406]  INFO -- : Report started at 2022-11-10 14:12:44 +0000
I, [2022-11-10T14:12:44.959133 #117406]  INFO -- : You are running ruby-grafana-reporter version 0.6.2.
D, [2022-11-10T14:12:45.228042 #117406] DEBUG -- : Document attributes: {"convert-backend"=>"pdf", "imagesdir"=>"./images", "var-template"=>"test"}
D, [2022-11-10T14:12:45.228424 #117406] DEBUG -- : Template ./templates/test.adoc contains 3 calls of grafana reporter functions.
D, [2022-11-10T14:12:45.311939 #117406] DEBUG -- : Processing SqlValueInlineMacro (instance: default, datasource: 1, sql: )
D, [2022-11-10T14:12:45.312099 #117406] DEBUG -- : Requesting [removed]/api/frontend/settings with '' and timeout '60'
D, [2022-11-10T14:12:45.345936 #117406] DEBUG -- : Received response #<Net::HTTPOK:0x000055e63c2aae40>
F, [2022-11-10T14:12:45.348503 #117406] FATAL -- : undefined method `id' for nil:NilClass
D, [2022-11-10T14:12:45.348989 #117406] DEBUG -- : Processing SqlValueInlineMacro (instance: default, datasource: 1, sql: select 1)
F, [2022-11-10T14:12:45.350099 #117406] FATAL -- : undefined method `id' for nil:NilClass
D, [2022-11-10T14:12:45.350389 #117406] DEBUG -- : Processing SqlValueInlineMacro (instance: default, datasource: 1, sql: select count(distinct prefix) from global_ip_rib;)
F, [2022-11-10T14:12:45.351419 #117406] FATAL -- : undefined method `id' for nil:NilClass
I, [2022-11-10T14:12:45.378211 #117406]  INFO -- : Report creation ended after 1 seconds with status 'finished'
```

**Application call**
 - type of call [webservice or single-run]: single-run
 - call of reporter [e.g. ruby-grafana-reporter -c myconfig]: 
 - call of report creation, if running as webservice [e.g. http://localhost/render?var-template=test]: `/home/ubuntu/.rbenv/versions/3.0.0/bin/ruby /home/ubuntu/.rbenv/versions/3.0.0/bin/ruby-grafana-reporter -t test -o test.pdf`

**Template file (if applicable)**
 - filename: test.adoc
 - relevant part of template file:
```
include::grafana_sql_value:1[sql="select 1",verbose_log="true"]
grafana_sql_value:1[sql="select 1",verbose_log="true"]
grafana_sql_value:1[sql="select count(distinct prefix) from global_ip_rib;"]
```

**Configuration file**
 - created with configuration wizard version [e.g. 0.3.0 or MANUAL]: 0.6.2 wizard
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
# This configuration has been built with the configuration wizard.

grafana:
  default:
    host: [host]
    api_key: [api_key]


grafana-reporter:
# Specifies how often the reporter shall check for newer versions [number of days].
# You may set check-for-updates to 0 to disable
  check-for-updates: 1
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 24
  webservice-port: 8815
# you may want to configure the following webhook callbacks to get informed on certain events
#  callbacks:
#    all:
#      - <<your_callback_url>>
#      - ...
#    on_before_create:
#      - <<your_callback_url>>
#      - ...
#    on_after_cancel:
#      - <<your_callback_url>>
#      - ...
#    on_after_finish:
#      - <<your_callback_url>>
#      - ...

default-document-attributes:
  imagesdir: ./images
# feel free to add here additional asciidoctor document attributes which are applied to all your templates
```

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: ubuntu 20.04
 - Grafana version [e.g. 6.3.4]: 7.2.2 (tested 8.3.5 and latest)
 - Environment [e.g. source, gem, docker or windows-exe]: gem
 - Ruby Version, if source or gem environment [e.g. 2.3.7]: 3.0.0
 - Reporter version [e.g. 0.3.0]: 0.6.2
