### ISSUE TITLE
grafana_panel_query_table: undefined method `each' for nil:NilClass stmt.each do

### ISSUE THREAD

**Issue by ilmarietto123** [divinity666/ruby-grafana-reporter#42]
**Describe the issue**
Hi and thanks for your great work!
I have this error trying to get tables:
```
ERROR -- : GrafanaReporterError: The datasource request to 'InfluxDB' (Grafana::InfluxDbDatasource) failed with an internal error: undefined method `each' for nil:NilClass
      stmt.each do |value|
          ^^^^^
```
I can get images, titles and descriptions from panels, but not tables.
Attached log and pdf.
If you need other info, I'm available.

Json of panel:
```
{
  "datasource": {
    "type": "influxdb",
    "uid": "0_MsV2Y4k"
  },
  "description": "",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "left",
        "cellOptions": {
          "type": "auto"
        },
        "inspect": false
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "purple",
            "value": null
          }
        ]
      },
      "color": {
        "mode": "fixed"
      },
      "displayName": "Produzione giornaliera",
      "unit": "kwatth"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Time"
        },
        "properties": [
          {
            "id": "unit",
            "value": "time:DD-MM-YYYY"
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 33,
    "w": 24,
    "x": 0,
    "y": 36
  },
  "id": 13,
  "options": {
    "showHeader": false,
    "footer": {
      "show": true,
      "reducer": [
        "sum"
      ],
      "countRows": false,
      "fields": "",
      "enablePagination": false
    },
    "sortBy": []
  },
  "pluginVersion": "9.4.7",
  "targets": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "0_MsV2Y4k"
      },
      "query": "import \"timezone\" \r\noption location=timezone.location(name: \"Europe/Rome\")\r\n\r\nfrom(bucket: \"Fotovoltaico_1h\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fotovoltaico\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"W_Tot\")\r\n  |> filter(fn: (r) => r[\"aggregate\"] == \"mean\")\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\r\n  |> timeShift(duration:-1s)\r\n  |> yield(name: \"sum\")",
      "refId": "A"
    }
  ],
  "title": "Fotovoltaico - Produzione giornaliera",
  "type": "table"
}
```

**Application call**
 - call of report creation, if running as webservice: http://172.29.0.9:8815/render?var-template=test_report&pdf-themesdir=/documents/themes

**Template file (if applicable)**
 - filename: test_report.adoc
 - relevant part of template file:
```

|===
include::grafana_panel_query_table:13[dashboard="UZFkI2L4z",verbose_log="true",query="A"]
|===

```

**Configuration file**
 - created with configuration wizard version: yes, wizard
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
# This configuration has been built with the configuration wizard.

grafana:
  default:
    host: http://172.29.0.9:3000
    api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


grafana-reporter:
# Specifies how often the reporter shall check for newer versions [number of days].
# You may set check-for-updates to 0 to disable
  check-for-updates: 1
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 720
  webservice-port: 8815
# you may want to configure the following webhook callbacks to get informed on certain events
#  callbacks:
#    all:
#      - <<your_callback_url>>
#      - ...
#    on_before_create:
#      - <<your_callback_url>>
#      - ...
#    on_after_cancel:
#      - <<your_callback_url>>
#      - ...
#    on_after_finish:
#      - <<your_callback_url>>
#      - ...

default-document-attributes:
  imagesdir: ./images
# feel free to add here additional asciidoctor document attributes which are applied to all your templates
```

**Environment (please complete the following information):**
 - OS [Alpine]: 
 - Grafana version: 9.4.7 (docker)
 - Environment: docker
 - Ruby Version, if source or gem environment [e.g. 2.3.7]: 3.1.4p223 (asciidoctor/docker-asciidoctor)
 - Reporter version [0.6.3]: 

[ruby grafana reporter error.log](https://github.com/divinity666/ruby-grafana-reporter/files/11415753/ruby.grafana.reporter.error.log)
[document.pdf](https://github.com/divinity666/ruby-grafana-reporter/files/11415789/document.pdf)
