### ISSUE TITLE
where to configure for HTML instead of default PDF report

### ISSUE THREAD

**Issue by SridharManoj-Parsi** [divinity666/ruby-grafana-reporter#43]
**Describe the issue**
i want to generate a html instead of PDF . but i am not able to find where i can configure this in grafana_reporter.config

**Configuration file**
 - created with configuration wizard version [e.g. 0.3.0 or MANUAL]: 
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
# This configuration has been built with the configuration wizard.
grafana:
  default:
    host: http://localhost:3000
    api_key: eyJrIjoiOXAwU2NFWHZXQk42amlTcUI4R2w3T01YbVlMS0cySEUiLCJuIjoic3JpIiwiaWQiOjF9


grafana-reporter:
# Specifies how often the reporter shall check for newer versions [number of days].
# You may set check-for-updates to 0 to disable
  check-for-updates: 1
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: i
  reports-folder: ./reports
  report-retention: 24
  webservice-port: 9094
# you may want to configure the following webhook callbacks to get informed on certain events
#  callbacks:
#    all:
#      - <<your_callback_url>>
#      - ...
#    on_before_create:
#      - <<your_callback_url>>
#      - ...
#    on_after_cancel:
#      - <<your_callback_url>>
#      - ...
#    on_after_finish:
#      - <<your_callback_url>>
#      - ...

default-document-attributes:
  imagesdir: ./images
# feel free to add here additional asciidoctor document attributes which are applied to all your templates
```
