### ISSUE TITLE
Simple stat pannel with two queries - reported values are the same

### ISSUE THREAD

**Issue by bolausson** [divinity666/ruby-grafana-reporter#49]
I partially managed to get a report - lets ignore tha fact that the image renderer plugin is not working (for whatever reason).

I created a simple stat panel to test ruby-grafana-reporter. It shows the energy consumption for two PDUs (left and right).
The power consumption is slightly different, but the report generated by ruby-grafana-reporter show the same value for both queries. 

Essentially I have two questions:

1. Where are the numbers in the report comming from? 1716819000000 I can't correlate it to any of the numbers shown in this panel. If I generate consecutive reports, the number keeps increasing though.
2. Why is it the same for both queries?
3. Any idea why the "Sum" query is showing an error in the report?

Below are the screenshots of the dashboard and the panel:
![PDU-Dashboard_edit](https://github.com/divinity666/ruby-grafana-reporter/assets/10600678/0eb1e2d6-4661-4170-a16e-6712f956c6eb)

![Panel-20](https://github.com/divinity666/ruby-grafana-reporter/assets/10600678/601548c7-ab23-4f21-9bd5-846b0985fea8)

This is a screenshot of the generated report:
![view_report](https://github.com/divinity666/ruby-grafana-reporter/assets/10600678/f8fa6427-dc7d-4fe5-a0a2-06d7d6b64a0a)

This is the generated PDF:
[view_report.pdf](https://github.com/divinity666/ruby-grafana-reporter/files/15458541/view_report.pdf)

**Application call**
 - type of call:
webservice
 - call of reporter:
` ruby-grafana-reporter -c grafana_reporter.config `
 - call of report creation, if running as webservice:
http://172.16.0.102:8815/render?var-template=power_report&from=now-3h&to=now&
(Via link in the Grafana Dashboard)

**Template file**
 - filename:
power_report.adoc
 - relevant part of template file (this is the entire template file):
```
= Lab energy consumption report

grafana_panel_image:20[dashboard="ediskdcksqz28e",width="100%"]

== Left PDU
grafana_panel_query_value:20[query="Left",dashboard="ediskdcksqz28e"]

== Right PDU
grafana_panel_query_value:20[query="Right",dashboard="ediskdcksqz28e"]

== Sum
grafana_panel_query_value:20[query="Sum",dashboard="ediskdcksqz28e"]
```

**Configuration file**
 - created with configuration wizard version: 
0.7.0 dev branch [32256e8]
 - relevant part of configuration file:
```
# This configuration has been built with the configuration wizard.
grafana:
  default:
    host: https://172.16.0.102:3000
    api_key: glsa_yyy_xxx

grafana-reporter:
  check-for-updates: 1
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 24
  webservice-port: 8815

default-document-attributes:
  imagesdir: ./images
```

**Environment:**
 - OS:
Ubuntu 22.04 
 - Grafana version:
v11.0.0 (277ef258d4
 - Environment:
Compiled from source using dev branch (added OpenSSL::SSL::VERIFY_NONE)
 - Ruby Version, if source or gem environment [e.g. 2.3.7]: 
ruby 3.0.2p107
gem 3.3.5
 - Reporter version [e.g. 0.3.0]:
 0.7.0 dev branch [32256e8]
