### ISSUE TITLE
Error during image rendering

### ISSUE THREAD

**Issue by ipats86** [divinity666/ruby-grafana-reporter#5]
Hello,
I am trying to export my first pdf report from a Grafana installation but unfortunately, I receive the below Fatal errors during the creation process.

FATAL -- : undefined method `[]' for nil:NilClass
FATAL -- : undefined method `id' for nil:NilClass
FATAL -- : uninitialized constant GrafanaReporter::PanelImageQuery::ImageCouldNotBeRenderedError
FATAL -- : undefined method `[]' for nil:NilClass
FATAL -- : undefined method `id' for nil:NilClass
FATAL -- : uninitialized constant GrafanaReporter::PanelImageQuery::ImageCouldNotBeRenderedError

**Application call**
 - type of call [webservice or single-run]: webservice
 - call of reporter [e.g. ruby-grafana-reporter -c myconfig]: /usr/local/rvm/rubies/ruby-2.7.0/bin/ruby /usr/local/rvm/gems/ruby-2.7.0/bin/ruby-grafana-reporter
 - call of report creation, if running as webservice [e.g. http://localhost/render?var-template=test]: http://[GRAFANA-FQDN]:8815/render?var-template=demo_report

**Template file (if applicable)**
 - filename: 
 - relevant part of template file:
```
<<part of your template file goes here>>
```

**Configuration file**
 - created with configuration wizard version [e.g. 0.3.0 or MANUAL]: Created with Configuration wizard (ruby-grafana-reporter -w)
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
grafana:
  default:
    host: http://localhost:3000
    api_key: XXXXXXXXXXXXXXXXXXXXXXXX

grafana-reporter:
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 24
  webservice-port: 8815
```

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: CentOS Linux release 7.8.2003
 - Environment [e.g. source, gem, docker or windows-exe]: gem
 - ruby Version, if source or gem environment [e.g. 2.3.7]: ruby 2.7.0p0 
 - reporter Version [e.g. 0.3.0]: v0.4.1
