### ISSUE TITLE
Configure domain for my Grafana and reportgenerator

### ISSUE THREAD

**Issue by hoouinkyouma** [divinity666/ruby-grafana-reporter#55]
Hi, I'm running grafana and ruby-grafana-reporter as a docker container and I have the respective volumes mounted to it.

My grafana is running on the domain, example: https://my-grafana.com => for accessing grafana

The ruby-reporter is running on 8815 port and my grafana_reporter.config, looks like this: 
````
grafana:
  default:
    host: https://my-grafana.com/ # 
    api_key: glsa_nnRscoPFJXXXX21

grafana-reporter:
# Specifies how often the reporter shall check for newer versions [number of days].
# You may set check-for-updates to 0 to disable
  check-for-updates: 7
  report-class: GrafanaReporter::Asciidoctor::Report
  templates-folder: ./templates
  reports-folder: ./reports
  report-retention: 168
  webservice-port: 8815

default-document-attributes:
  imagesdir: ./images
````

Since, you can see, my host, I have mentioned my domain name instead of the ip and the port number. For the reports part on the Grafana, I created a link and added the URL: https://my-grafana.com/report/render?var-template=report.adoc. (report.adoc is the file name in my local.)

When I try to generate the reports, this is what I see in my next window: 

![Screenshot 2024-06-20 145325](https://github.com/divinity666/ruby-grafana-reporter/assets/103956306/c007c259-5918-41b8-815c-ae1f6b432c1e)

Now, I'm wondering, why it'd say that? I have a target group and listeners configured correctly. Can you please help on resolving this? How would I go about adding my domain and use it for reporting instead of using the ip address and the port number?
