### ISSUE TITLE
Support email sending in single-run mode

### ISSUE THREAD

**Issue by chicco785** [divinity666/ruby-grafana-reporter#64]
**Describe the issue**

I would like to be able to send email including the generated report within single-run mode. This would be very useful to schedule job generation reports in a k8s and send reports to no IT users.

Would you accept a PR?

**Application call**
 - type of call: single-run 

**Template file**

N/A

**Configuration file**

This is the proposed configuration addition:

```
email:
  enabled: true
  smtp_address: smtp.freesmtpservers.com
  smtp_port: 25
  from: outgoing@example.com
  body: Top report is top top here
  subject: Report subject
  enable_starttls_auto: true
  to: 
    - incoming@example.com
```

smtp user and passwords should be loaded from env variables

**Environment (please complete the following information):**

N/A
